[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "vlm-monitor"
dynamic = ["version"]
description = "A second set of eyes."
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
authors = [{name = "Salman Naqvi", email = "s1148093@s.eduhk.hk"}]
keywords = ['nbdev', 'vlms', 'llms', 'computer vision', 'natural language processing']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = ['fastcore==2.2.13','fastlite','python-fastllm==0.0.36','aidialog==0.0.6','fastprogress','tiktoken','pycachy']

[project.urls]
Repository = "https://github.com/ForBo7/vlm-monitor"
Documentation = "https://ForBo7.github.io/vlm-monitor/"

[project.entry-points.nbdev]
vlm_monitor = "vlm_monitor._modidx:d"

[tool.setuptools.dynamic]
version = {attr = "vlm_monitor.__version__"}

[tool.setuptools.packages.find]
include = ["vlm_monitor"]

[tool.nbdev]
allowed_metadata_keys = ['solveit']
allowed_cell_metadata_keys = ['solveit_ai']
