# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/vlm-monitor',
                'doc_host': 'https://ForBo7.github.io',
                'git_url': 'https://github.com/ForBo7/vlm-monitor',
                'lib_path': 'vlm_monitor'},
  'syms': {'vlm_monitor.core': {'vlm_monitor.core.foo': ('core.html#foo', 'vlm_monitor/core.py')}}}
