"""Fill in a module description here

Docs: https://ForBo7.github.io/vlm-monitorcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['Video', 'Frame', 'Run', 'RunFrame', 'DBResources', 'init_db']

# %% ../nbs/00_core.ipynb #1654310c
from fastcore.all import *

# %% ../nbs/00_core.ipynb #22ed8677
class Video: id:int; title:str=''; overview:str=''; transcript:str=''; length:int=0; sample_rate:int=0
class Frame: id:int; video_id:int; frame_number:int; subtitle:str=''
class Run: id:int; deploy_time:str; finish_time:str; request_timer:str; video_id:int; model:str; usage:str; num_frames:int; description:str
class RunFrame: run_id:int; frame_id:int; type:str; system_prompt:str; prompt:str; description:str; usage:str

# %% ../nbs/00_core.ipynb #83cc5be2
from fastlite import *

# %% ../nbs/00_core.ipynb #8206ddbc
from typing import NamedTuple
from apswutils.db import Database, Table
class DBResources(NamedTuple): db:Database; videos:Table; frames:Table; runs:Table; runframes:Table

# %% ../nbs/00_core.ipynb #c0067b7e
def init_db(
    path:str|Path='db.db' # Path to database
) -> DBResources:
    "Initialize a database and return the database, as well as its videos, frames, runs, and runframes tables."
    db = database(path)
    videos = db.create(Video, transform=True)
    frames = db.create(Frame, transform=True, foreign_keys=[('video_id', 'video', 'id')])
    runs = db.create(Run, transform=True)
    runframes = db.create(RunFrame, pk=['run_id', 'frame_id', 'type'], foreign_keys=[('run_id', 'run', 'id'), ('frame_id', 'frame', 'id')], transform=True)
    return DBResources(db, videos, frames, runs, runframes)


# %% ../nbs/00_core.ipynb #6dc5f4be
from fastllm.types import Msg, Part, PartType
