"""Fill in a module description here

Docs: https://ForBo7.github.io/vlm-monitorcore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['tz', 'Video', 'Frame', 'Run', 'RunFrame', 'DBResources', 'init_db', 'user', 'assistant', 'stream', 'img2b64',
           'session', 'deploy_run', 'summarize_window']

# %% ../nbs/00_core.ipynb #1654310c
from fastcore.all import *

# %% ../nbs/00_core.ipynb #22ed8677
class Video: id:int; title:str=''; overview:str=''; transcript:str=''; length:int=0; sample_rate:int=0
class Frame: id:int; video_id:int; frame_number:int; subtitle:str=''
class Run: id:int; deploy_time:str; finish_time:str; request_timer:str; video_id:int; model:str; usage:str; num_frames:int; description:str
class RunFrame: run_id:int; frame_id:int; type:str; system_prompt:str; prompt:str; description:str; usage:str

# %% ../nbs/00_core.ipynb #83cc5be2
from fastlite import *

# %% ../nbs/00_core.ipynb #8206ddbc
from typing import NamedTuple
from apswutils.db import Database, Table
class DBResources(NamedTuple): db:Database; videos:Table; frames:Table; runs:Table; runframes:Table

# %% ../nbs/00_core.ipynb #c0067b7e
def init_db(
    path:str|Path='db.db' # Path to database
) -> DBResources:
    "Initialize a database and return the database, as well as its videos, frames, runs, and runframes tables."
    db = database(path)
    videos = db.create(Video, transform=True)
    frames = db.create(Frame, transform=True, foreign_keys=[('video_id', 'video', 'id')])
    runs = db.create(Run, transform=True)
    runframes = db.create(RunFrame, pk=['run_id', 'frame_id', 'type'], foreign_keys=[('run_id', 'run', 'id'), ('frame_id', 'frame', 'id')], transform=True)
    return DBResources(db, videos, frames, runs, runframes)


# %% ../nbs/00_core.ipynb #6dc5f4be
from fastllm.types import Msg, Part, PartType

# %% ../nbs/00_core.ipynb #275b9ad0
def user(
    txt:str,
    img:str|None=None,
)->Msg:
    "Build a user message with optional image."
    if img is None: return Msg(role='user', content=[Part(type=PartType.text, text=txt)])
    else: return Msg(role='user', content=[Part(type=PartType.input_image, text=img), Part(type=PartType.text, text=txt)])

# %% ../nbs/00_core.ipynb #46f2c4a6
def assistant(
    txt:str,
    data:dict={'citations':[]},
)->Msg:
    "Build an assistant message."
    return Msg(role='assistant', content=[Part(type=PartType.text, text=txt, data=data)])

# %% ../nbs/00_core.ipynb #9fb8d657
from fastllm.acomplete import acomplete

# %% ../nbs/00_core.ipynb #8e3ee7f7
from fastllm.types import Completion
async def stream(
    msgs:list|None=None,  # Messages to send
    model:str='',  # Model name (e.g. 'deepseek-v4-flash')
    max_think:float=float('inf'),  # Max thinking tokens to display
    usage:bool=True,  # Show usage info in output
    display:bool=True,  # Print text/thinking as it arrives
    **kwargs,  # Passed to acomplete
) -> Completion:  # Return the final completion
    "Stream a response, printing text/thinking as it arrives. Returns the final completion."
    assert msgs is not None, 'no messages provided'
    assert model!='', 'no model name provided'
    think_cnt, seen_txt = 0, False
    async for o in await acomplete(msgs, model, stream=True, **kwargs):
        if not isinstance(o, Completion) and display:
            if o.get('thinking') and think_cnt<max_think: print('🤔', end='', flush=True)
            if txt:=o.get('text'): print(f"{'\n\n' if not seen_txt else ''}{txt}", end='', flush=True) or not seen_txt and (seen_txt:=True)
            think_cnt+=1
    if display: print()
    return o

# %% ../nbs/00_core.ipynb #3f8625b7
from base64 import b64encode
def img2b64(
    path:Path,
)->str:
    "Encode an image file as a base64 data URL."
    return 'data:image/png;base64,'+b64encode(Path.read_bytes(path)).decode()

# %% ../nbs/00_core.ipynb #28071d39
@delegates(stream, keep=True)
def session(
    **kwargs,
):
    "Create a stream partial with preset model/kwargs."
    return partial(stream, **kwargs)

# %% ../nbs/00_core.ipynb #b024c39d
async def _process_frame(session, run_id:int, p:Path, prompt:str, prompt_type:str):
    "Run VLM on a single frame and store the result."
    r = await session([user(prompt, img=img2b64(p))])
    runframes.insert(run_id=run_id, frame_id=p.stem.split('_')[1], type=prompt_type, prompt=prompt, description=r.message.text, usage=r.usage.raw)

# %% ../nbs/00_core.ipynb #e5e1041f
from datetime import datetime
from zoneinfo import ZoneInfo

tz = ZoneInfo('Asia/Hong_Kong')

def _run_header(run, model:str, start:int, stop:int, step:int, cache:bool):
    "Print run header box."
    print(f'╭─ Run #{run.id} ═══════════════════════════════╮\n│ Model    {model}\n│ Start    {start}\n│ Stop     {stop}\n│ Step     {step}\n│ Frames   {(stop-start)//step}\n│ Cache    {cache}\n│ Time     {datetime.now(tz).strftime("%H:%M:%S")}\n╰──────────────────────────────────────────────╯')

# %% ../nbs/00_core.ipynb #494b389e
def _finish_run(run_id:int)->Run:
    "Update run with finish time and usage, print summary box."
    runs.update(id=run_id, finish_time=datetime.now(tz), request_timer=None, usage=compute_usage(run_id))
    run = runs[run_id]
    tot = dict2obj(loads(run.usage))
    elapsed = datetime.fromisoformat(run.finish_time) - datetime.fromisoformat(run.deploy_time)
    print(f'╭─ Run #{run.id} Complete ═════════════════════╮\n│ Finish   {datetime.fromisoformat(run.finish_time).strftime("%H:%M:%S")}\n│ Elapsed  {str(elapsed).split(".")[0]}\n│ Cost     ${tot.cost:.4f} (HKD {tot.cost*7.84:.2f})\n╰──────────────────────────────────────────────╯')
    return run

# %% ../nbs/00_core.ipynb #e5822553
def _run_header(run, model:str, start:int, stop:int, step:int, cache:bool):
    "Print run header box."
    print(f'╭─ Run #{run.id} ═══════════════════════════════╮\n│ Model    {model}\n│ Start    {start}\n│ Stop     {stop}\n│ Step     {step}\n│ Frames   {(stop-start)//step}\n│ Cache    {cache}\n│ Time     {datetime.now(tz).strftime("%H:%M:%S")}\n╰──────────────────────────────────────────────╯')

# %% ../nbs/00_core.ipynb #3d51e72c
from fastprogress.fastprogress import NBMasterBar as master_bar
async def deploy_run(
    video_id:int,
    session,
    pth:list,
    prompt:str,
    prompt_type:str,
    start:int=0,
    stop:int|None=None,
    step:int=1,
    cache:bool=False,
)->Run:
    "Run a single prompt across a range of frames, storing results in the database."
    if stop is None: stop = len(pth)
    if not cache: disable_cachy(); print('!! Cache disabled')
    else: print('!! Using cache')

    run = runs.insert(deploy_time=datetime.now(tz), video_id=video_id, model=session.keywords['model'], num_frames=(stop-start)//step)
    _run_header(run, session.keywords['model'], start, stop, step, cache)

    for p in (mb:=master_bar(pth[start:stop:step])):
        mb.main_bar.comment = f'frame {p.stem.split("_")[1]}'
        await _process_frame(session, run.id, p, prompt, prompt_type)

    if not cache: enable_cachy(); print('!! Cache enabled')
    return _finish_run(run.id)

# %% ../nbs/00_core.ipynb #552a05ab
from tiktoken import encoding_for_model

# %% ../nbs/00_core.ipynb #79240a71
def _build_window(run_id:int, start:int, stop:int, step:int=1)->tuple[str,int]:
    "Query runframes and build the window text with token count."
    rows = L(runframes.rows_where(where='run_id=? AND frame_id>=? AND frame_id<?', where_args=(run_id, start, stop)))
    grouped = rows.groupby(lambda r: r['frame_id'])
    fids = sorted(grouped.keys())
    if step > 1: fids = fids[::step]

    window = ''
    for fid in fids:
        prefix = f'\n\nTimestamp ({fid}s)\n'
        window += prefix + len(prefix.strip())*'='
        for d in grouped[fid]: window += f"\n\n--\n\n{d['type'].upper()}\n\n{d['description']}"

    enc = encoding_for_model('gpt-4o')
    return window, len(enc.encode(window))

# %% ../nbs/00_core.ipynb #87d7fe2a
def _summary_header(run_id:int, start:int, stop:int, step:int, model:str, window:str, win_tokens:int, cache:bool, t0:datetime):
    "Print summary run header box."
    print(f'╭─ Summary Run #{run_id} ═══════════════════════╮\n│ Frames   {start}–{stop} (step {step})\n│ Model    {model}\n│ Window   {len(window)} chars / {win_tokens} tokens\n│ Cache    {cache}\n│ Start    {t0.strftime("%H:%M:%S")}\n╰──────────────────────────────────────────────╯')

# %% ../nbs/00_core.ipynb #8ce0100c
def _summary_footer(summary:str, win_tokens:int, t0:datetime, t1:datetime, cost:float):
    "Print summary completion box."
    enc = encoding_for_model('gpt-4o')
    sum_tokens = len(enc.encode(summary))
    reduction = (1 - sum_tokens/win_tokens)*100 if win_tokens else 0
    elapsed = t1 - t0
    print(f'╭─ Summary Complete ═══════════════════════════╮\n│ Finish   {t1.strftime("%H:%M:%S")}\n│ Elapsed  {str(elapsed).split(".")[0]}\n│ Summary  {len(summary)} chars / {sum_tokens} tokens\n│ Reduced  {reduction:.1f}%\n│ Cost     ${cost:.4f} (HKD {cost*7.84:.2f})\n╰──────────────────────────────────────────────╯')

# %% ../nbs/00_core.ipynb #9faeeaea
async def summarize_window(
    run_id:int,
    start:int,
    stop:int,
    session,
    sys_prompt:str,
    step:int=1,
    cache:bool=False,
)->str:
    "Summarize a window of frames from runframes. Returns summary text."
    if not cache: disable_cachy()

    window, win_tokens = _build_window(run_id, start, stop, step)
    t0 = datetime.now(tz)
    _summary_header(run_id, start, stop, step, session.keywords['model'], window, win_tokens, cache, t0)

    r = await session([user(window)], system=sys_prompt)
    t1 = datetime.now(tz)

    if not cache: enable_cachy()

    summary = r.message.text
    _summary_footer(summary, win_tokens, t0, t1, r.usage.raw.get('cost', 0))
    return summary
